---
title: "MGSC 661 - Midterm Project"
output: html_notebook
---


# Importing data
```{r}
require(visreg)
require(glue)
require(car)
require(lmtest)
require(splines)
require(psych)
require(stargazer)
require(plm)
require(ggplot2)
require(ggtext)
require(ggpubr)
require(ggrepel)
require(ggthemes)
require(scales)
require(caTools)
require(methods)
require(boot)
require(tidyverse)

windowsFonts(Helvetica = "Product Sans")
```

```{r}
theme_lox <- function() {
  theme(
    panel.grid.major.x = element_line(linewidth = 0.3, colour = "#cbcbcb"),
    panel.grid.major.y = element_line(linewidth = 0.3, colour = "#cbcbcb"),
    plot.title = element_markdown(
      family = "Helvetica",
      size = 22,
      face = "bold",
      color = "#222222"
    ),
    plot.subtitle = element_text(
      family = "Helvetica",
      size = 16,
      margin = margin(2, 0, 2, 0)
    ),
    plot.caption = element_text(family = "Helvetica", face = "bold"),
    axis.text = element_text(
      family = "Helvetica",
      size = 12,
      color = "#222222"
    ),
    axis.title = element_text(
      family = "Helvetica",
      size = 14,
      color = "#222222"
    ),
    legend.text = element_text(family = "Helvetica", size = 12),
    legend.title = element_text(
      family = "Helvetica",
      size = 14,
      face = "bold"
    ),
    legend.position = "right",
    strip.text = element_text(
      family = "Helvetica",
      size = 12,
      hjust = 0.5
    )
  )
}
```

```{r}
data <- read.csv("./IMDB_data_Fall_2023.csv")
attach(data)
```

# Exploratory data analysis

```{r}
head(data)
summary(data)
```


## Data cleaning

```{r}
data[duplicated(data)]
```
## Univariate distributions

### Target variable
```{r}
ggplot(data, aes(x = imdb_score)) +
  geom_histogram(binwidth = 1) +
  scale_x_continuous(breaks = breaks_width(width = 1)) +
  labs(x = "IMDb Rating", y = "Number of movies", title = "Distribution of ratings") +
  theme_pubr() +
  theme_lox()
```

### Movie budget
```{r}
ggplot(data, aes(x = movie_budget)) +
  geom_histogram(bins = 20) +
  scale_x_continuous(breaks = breaks_pretty(), labels = label_dollar(scale_cut = cut_short_scale())) +
  labs(x = "Movie budget", y = "Number of movies", title = "Distribution of movie budgets") +
  theme_pubr() +
  theme_lox()
```

### Release year
```{r}
ggplot(data, aes(x = release_year)) +
  geom_histogram(bins = 10) +
  scale_x_continuous(breaks = breaks_pretty(n = 10)) +
  labs(x = "Release Year", y = "Number of movies", title = "Distribution of release year") +
  theme_pubr() +
  theme_lox()
```

### Number of faces
```{r}
ggplot(data, aes(x = nb_faces)) +
  geom_histogram() +
  scale_x_continuous(breaks = breaks_pretty()) +
  labs(x = "Number of faces", y = "Number of movies", title = "Distribution of number of faces in the movie poster") +
  theme_pubr() +
  theme_lox()
```

### Duration
```{r}
ggplot(data, aes(x = duration)) +
  geom_boxplot() +
  scale_x_continuous(breaks = breaks_pretty()) +
  labs(x = "Duration", title = "Boxplot of movie duration") +
  theme_pubr() +
  theme_lox() +
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank())
```

## Bivariate distributions

### Movie budgets ~ IMDb Score
```{r}
ggplot(data, aes(x = movie_budget, y = imdb_score)) +
  geom_point() +
  geom_text_repel(aes(label = movie_title), size = 3, max.overlaps = 5, nudge_y = 0.5) +
  scale_x_continuous(breaks = breaks_pretty(), labels = label_dollar(scale_cut = cut_short_scale())) +
  labs(x = "Movie budget", y = "IMDb Score", title = "Movie budget and IMDb score") +
  theme_pubr() +
  theme_lox()
```

### Duration ~ IMDb Score
```{r}
ggplot(data, aes(x = duration, y = imdb_score)) +
  geom_point() +
  geom_text_repel(aes(label = movie_title), size = 3, max.overlaps = 10, nudge_y = 0.5) +
  scale_x_continuous(breaks = breaks_pretty(), labels = label_number()) +
  labs(x = "Duration", y = "IMDb Score", title = "Movie duration and IMDb score") +
  theme_pubr() +
  theme_lox()
```

### Genre ~ IMDb Score
```{r}
data %>%
  select(movie_id, imdb_score, action:crime) %>%
  pivot_longer(cols = c(-imdb_score, -movie_id), names_to = "genre") %>%
  mutate(genre = str_to_sentence(genre)) %>%
  group_by(genre) %>%
  filter(value == 1) %>%
  summarise(avg_score = mean(imdb_score), num_movies = n()) %>%
  ggplot(aes(x = genre, y = avg_score, fill = genre)) +
  geom_col() +
  geom_text_repel(aes(y = avg_score, label = num_movies), nudge_y = 0.1) +
  scale_fill_tableau(palette = "Tableau 20") +
  scale_y_continuous(breaks = breaks_pretty(), limits = c(0, 10)) +
  guides(fill = "none") +
  labs(x = "Genre", y = "Average IMDb Score", title = "Average IMDb score by genre") +
  theme_pubr() +
  theme_lox() +
  theme(panel.grid.major.x = element_blank())
```

```{r fig.width = 10}
data %>%
  select(movie_id, movie_title, imdb_score, action:crime) %>%
  pivot_longer(cols = c(-imdb_score, -movie_id, -movie_title), names_to = "genre") %>%
  mutate(genre = str_to_sentence(genre)) %>%
  group_by(genre) %>%
  filter(value == 1) %>%
  ggplot(aes(x = genre, y = imdb_score, fill = genre)) +
  geom_boxplot() +
  scale_fill_tableau(palette = "Tableau 20") +
  scale_y_continuous(breaks = breaks_pretty(), limits = c(0, 10)) +
  guides(fill = "none") +
  labs(x = "Genre", y = "IMDb Score", title = "Boxplot of IMDb score by genre", caption = "Movies span across genres") +
  theme_pubr() +
  theme_lox()
```

### Release Month ~ IMDb Score
```{r}
data %>%
  mutate(release_date = dmy(str_c(release_day, release_month, release_year, sep = "-"))) %>%
  mutate(release_month = month(release_date, label = TRUE)) %>%
  ggplot(aes(x = release_month, y = imdb_score, fill = release_month)) +
  geom_boxplot(outlier.size = 3) +
  geom_text_repel(aes(label = movie_title), max.overlaps = 5) +
  scale_fill_tableau(palette = "Tableau 20") +
  scale_y_continuous(breaks = breaks_pretty(), limits = c(0, 10)) +
  guides(fill = "none") +
  labs(x = "Release Month", y = "IMDb Score", title = "Boxplot of IMDb score by release month") +
  theme_pubr() +
  theme_lox()
```

### Actor 1 ~ IMDb Score

```{r fig.width = 12, fig.height = 8}
data %>%
  filter(actor1 %in% (
    data %>%
      group_by(actor1) %>%
      count(sort = TRUE) %>%
      head(10)
  )$actor1) %>%
  ggplot(aes(
    x = fct_reorder(actor1, imdb_score, .fun = median),
    y = imdb_score,
    fill = actor1
  )) +
  geom_boxplot(outlier.size = 3) +
  geom_text_repel(aes(label = movie_title), max.overlaps = 7) +
  scale_fill_tableau(palette = "Tableau 20") +
  scale_y_continuous(breaks = breaks_pretty(), limits = c(0, 10)) +
  guides(fill = "none") +
  labs(
    x = "Actor 1 Name",
    y = "IMDb Score",
    title = "Boxplot of IMDb score by Actor 1",
    subtitle = "Top 10 actors by number of movies shown"
  ) +
  theme_pubr() +
  theme_lox() +
  coord_flip()

```

### Distributor ~ IMDb Score
```{r fig.width = 12, fig.height=8}
data %>%
  filter(distributor %in%
           (data %>%
              group_by(distributor) %>%
              count(sort = TRUE) %>%
              head(10))$distributor) %>%
  ggplot(aes(x = distributor, y = imdb_score, fill = distributor)) +
  geom_boxplot(outlier.size = 3) +
  geom_text_repel(aes(label = movie_title), max.overlaps = 5) +
  scale_fill_tableau(palette = "Tableau 20") +
  scale_y_continuous(breaks = breaks_pretty(), limits = c(0, 10)) +
  guides(fill = "none") +
  labs(
    x = "Distributor",
    y = "IMDb Score",
    title = "Boxplot of IMDb score by distributor",
    subtitle = "Top 10 distributors by number of movies shown"
  ) +
  theme_pubr() +
  theme_lox() +
  coord_flip()
  
```

